### ISSUE TITLE
bireme是怎样保证数据一致性?

### ISSUE THREAD

**Issue by shubifeng** [HashDataInc/bireme#91]
kafka消费存在指定多个Partition时, 会不会在执行update时导致先后顺序问题?

bireme消费过程中出现异常,  好像没有看到数据重新打回到kafka, 那么就可能会造成数据丢失不一致的情况.

**Comment by wangzw** [comment]
Good questions.

If you use Debezium as the CDC and configure Kafka with multiply partitions for a topic. Bireme cannot  guarantee the loading order and will throw exception.

It is ok to use Maxwell with multiply Kafka partitions since Maxwell hash binlong entry with table name. 

Bireme only commit to Kafka after committing to database. So it is ok to stop/interrupt Bireme at any point and continue later.
